data class Post(
    var id: Int = 0,
    val ownerId: Int,
    val fromId: Int,
    val createdBy : Int,
    val date: Long,
    val text: String,
    val replyOwnerId: Int,
    val replyPostId: Int,
    val friendsOnly: Boolean,
    val comments: Comments,
    val copyright : Copyright,
    val likes: Likes,
    val reposts : Reposts,
    val views : Views,
    val postType : String,
    val postSource : PostSource?,
    val attachments : Array<Attachment>? = emptyArray(),
    val geo : Geo?,
    val signerId : Int,
    val copyHistory : Array<Post>? = emptyArray(),
    val canPin : Boolean,
    val canDelete : Boolean,
    val canEdit : Boolean,
    val isPinned : Boolean,
    val markedAsAds : Boolean,
    val isFavorite : Boolean,
    val postponedId : Int
)